# Generated by Django 3.0.3 on 2020-02-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200218_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='news/thumbnail/'),
        ),
    ]
